
run:
	vsim -do DE1_SoC_Computer_run_msim_rtl_verilog.do work.DE1_SoC_Computer -L Computer_System -L /home/matt/de1-soc/DE1-SoC_Computer_15_640_video_only/verilog/simulation/modelsim/HPS -L /home/matt/altera_lite/15.1/modelsim_ase/altera/verilog/220model -L /home/matt/altera_lite/15.1/modelsim_ase/altera/verilog/altera_lnsim -L /home/matt/altera_lite/15.1/modelsim_ase/altera/verilog/altera_mf -L /home/matt/altera_lite/15.1/modelsim_ase/altera/verilog/cyclonev
