// system.v

// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module system (
		input  wire  clk_clk,         //       clk.clk
		input  wire  reset_reset_n,   //     reset.reset_n
		output wire  vga_clk_clk,     //   vga_clk.clk
		output wire  vga_reset_reset  // vga_reset.reset
	);

	system_video_pll_0 video_pll_0 (
		.ref_clk_clk        (clk_clk),         //      ref_clk.clk
		.ref_reset_reset    (~reset_reset_n),  //    ref_reset.reset
		.vga_clk_clk        (vga_clk_clk),     //      vga_clk.clk
		.reset_source_reset (vga_reset_reset)  // reset_source.reset
	);

endmodule
