KDIR ?= /lib/modules/$(shell uname -r)/build
PWD := $(shell pwd)

modules :
	$(MAKE) -C $(KDIR) M=$(PWD) modules

modules_install :
	$(MAKE) -C $(KDIR) M=$(PWD) modules_install

clean :
	$(MAKE) -C $(KDIR) M=$(PWD) clean
