// ip.v

// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module ip (
		input  wire  clk_clk,                  //                  clk.clk
		output wire  pll_0_outclk12288mhz_clk, // pll_0_outclk12288mhz.clk
		output wire  pll_0_outclk2592mhz_clk,  //  pll_0_outclk2592mhz.clk
		input  wire  reset_reset_n             //                reset.reset_n
	);

	ip_pll_0 pll_0 (
		.refclk   (clk_clk),                  //  refclk.clk
		.rst      (~reset_reset_n),           //   reset.reset
		.outclk_0 (pll_0_outclk12288mhz_clk), // outclk0.clk
		.outclk_1 (pll_0_outclk2592mhz_clk),  // outclk1.clk
		.locked   ()                          // (terminated)
	);

endmodule
